dist: trusty
language: generic

env:
  global:
    - ENCRYPTION_LABEL: "34ab45136e05"
    - EXTRA_FILES="*.png"
    - DEPLOY_USER="annevankesteren"

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
