language: generic

env:
  global:
    - ENCRYPTION_LABEL="34ab45136e05"
    - EXTRA_FILES="*.png"

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
