dist: trusty
language: generic

env:
  global:
    - ENCRYPTION_LABEL: "34ab45136e05"
    - EXTRA_FILES="*.png"
    - DEPLOY_USER="annevankesteren"

script:
  - make deploy

notifications:
  email:
    on_success: never
    on_failure: always
